import contextlib
with contextlib.redirect_stdout(None):
    import pygame
pygame.init()

DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 800

BACKGROUND_WH = (DISPLAY_WIDTH, DISPLAY_HEIGHT)

CLOCK_SPEED = 60

ANIM_FRAMES = CLOCK_SPEED // 10

PLAYER_HEALTH = 1
PLAYER_LIVES = 3
PLAYER_SPEED = DISPLAY_WIDTH // 200
PLAYER_WH = (DISPLAY_WIDTH // 16, DISPLAY_HEIGHT // 13)
PLAYER_BULLET_COLOR = 7, 238, 255
NUM_PLAYER_BULLETS = 5
PLAYER_BULLET_SPEED = DISPLAY_HEIGHT // 133

NUM_ENEMIES = 40
ENEMY_HEALTH = 1
ENEMY_SPEED = DISPLAY_WIDTH // 800
ENEMY_WH = (DISPLAY_WIDTH // 20, DISPLAY_HEIGHT // 17)
ENEMY_BULLET_COLOR = 255, 100, 100
ENEMY_BULLET_SPEED = DISPLAY_HEIGHT // 266
ENEMY_FIRE_CHANCE = .05

BULLET_WH = (DISPLAY_WIDTH // 300, DISPLAY_HEIGHT // 66)
